### PR TITLE
Extract styling for Button component, add display options and Storybook stories

### PR DESCRIPTION
**Pull request by jaredcwhite**
(Note: branched this off of `more-bloom` branch in anticipation of that getting merged into master soon)

### CODE REVIEW

**Comment by bk3c** [comment]
@jaredcwhite more-bloom is merged, but since I have it set to always squash it loses the reference to the more-bloom branch HEAD since it doesn't exist in master now. I say all this having made the exact same mistake last week. You should be able to rebase your commits from master, though.

**Comment by jaredcwhite** [comment]
> @jaredcwhite more-bloom is merged, but since I have it set to always squash it loses the reference to the more-bloom branch HEAD since it doesn't exist in master now. I say all this having made the exact same mistake last week. You should be able to rebase your commits from master, though.

Yeah, the PR diff is still noisy, so I'll rebase…

**Comment by jaredcwhite** [comment]
OK, rebase worked, other than it's showing changes to a couple of readme files but I can't see any visible change at all. Maybe a hidden character difference or something…

**Comment by jaredcwhite** [comment]
I think this is ready to roll now, barring additional feedback. I renamed `Button` to `LinkButton` and created a proper `Button` that accepts a click handler. CSS is shared between both. Storybook stories are in place for both of them.

**Comment by bk3c** [comment]
@jaredcwhite Everything looks good to me, and good catch on the previously-missing polyglot types. Can you knock out that last merge conflict, and I'll push it in?

**Comment by jaredcwhite** [comment]
@bk3c OK, got the conflict fixed. Should be ready to roll!

**Pull request merged**
